name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=all Flask pandas plotly pydantic pydantic-settings

      - name: Test core functionality
        run: |
          python -c "
          print('=== Testing Core Functionality ===')
          
          # Test imports
          from src.gemini_ird_pricer.parsing import parse_notional, parse_maturity_date
          from src.gemini_ird_pricer.config import get_config
          from src.gemini_ird_pricer.services import build_services
          from src.gemini_ird_pricer import create_app
          print('✅ All imports successful')
          
          # Test parsing
          notional = parse_notional('10m')
          print(f'✅ Parse notional: {notional:,.0f}')
          
          maturity = parse_maturity_date('5y')
          print(f'✅ Parse maturity: {maturity.strftime(\"%Y-%m-%d\")}')
          
          # Test config
          config = get_config()
          print(f'✅ Config loaded: ENV={config.ENV}')
          
          # Test services
          services = build_services(config)
          print('✅ Services built successfully')
          
          # Test Flask app
          app = create_app()
          print('✅ Flask app created successfully')
          
          with app.app_context():
              routes = [str(rule) for rule in app.url_map.iter_rules()]
              print(f'✅ Routes registered: {len(routes)} routes')
          
          print('\\n✅ All tests passed - Application is working correctly!')
          "

  build-docker:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: gemini-ird-pricer:ci
